name: Astra CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Build Backend
        working-directory: backend
        run: npm run build

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Build Backend Docker Image
        run: docker build -t astra-backend ./backend

      - name: Build Frontend Docker Image
        run: docker build -t astra-frontend ./frontend